apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pushgateway-exact-correlation
  namespace: observability
  labels:
    alertmanagerConfig: main
spec:
  route:
    groupBy: ['alertname', 'correlation_id']
    groupWait: 5s
    groupInterval: 30s
    repeatInterval: 2m
    receiver: 'pushgateway-correlation-webhook'

  receivers:
  - name: 'pushgateway-correlation-webhook'
    webhookConfigs:
    - url: 'https://webhook-test.com/b05fc179dd8b97132b436df4cb3dfdd1'
      sendResolved: true