apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.webapp.name }}-nginx-config
  labels:
    app: {{ .Values.webapp.name }}
    {{- include "tracing-app.labels" . | nindent 4 }}
data:
  default.conf: |
    {{ .Files.Get "files/nginx.conf" | nindent 4 }}